/*
    ChibiOS - Copyright (C) 2006..2016 Giovanni Di Sirio
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/*
    Generated by gen-board.h.py based on board.yaml
*/

#ifndef _BOARD_H_
#define _BOARD_H_


/*
    Setup for smalltime
*/

/*
    Board identifier
*/
#define BOARD_
#define BOARD_NAME                     "smalltime"

/*
    Board oscillators-related settings.
*/
#if !defined(STM32_LSECLK)
#define STM32_LSECLK                   0U
#endif

#if !defined(STM32_HSECLK)
#define STM32_HSECLK                   0U
#endif

/*
    Board voltages
    Required for performance limits calculation.
*/
#define STM32_VDD                      330U

/*
    MCU type as defined in the ST header.
*/
#define STM32F051x8

/*
    IO pins assignments.
*/
#define GPIOA_DIG2                     0U
#define GPIOA_DIG8                     1U
#define GPIOA_DIG7                     2U
#define GPIOA_LIGHT_EN                 3U
#define GPIOA_LIGHT_SENSE              4U
#define GPIOA_DIG5                     5U
#define GPIOA_SEG_E                    6U
#define GPIOA_SEG_D                    7U
#define GPIOA_SW_INC                   8U
#define GPIOA_SW_SET                   9U
#define GPIOA_DIG6                     10U
#define GPIOA_PIN11                    11U
#define GPIOA_SEG_B                    12U
#define GPIOA_SWDIO                    13U
#define GPIOA_SWCLK                    14U
#define GPIOA_DIG1                     15U

#define GPIOB_SEG_C                    0U
#define GPIOB_SEG_DP                   1U
#define GPIOB_PIN2                     2U
#define GPIOB_SEG_A                    3U
#define GPIOB_SEG_F                    4U
#define GPIOB_SEG_G                    5U
#define GPIOB_I2C_SCL                  6U
#define GPIOB_I2C_SDA                  7U
#define GPIOB_PIN8                     8U
#define GPIOB_PIN9                     9U
#define GPIOB_PIN10                    10U
#define GPIOB_PIN11                    11U
#define GPIOB_PIN12                    12U
#define GPIOB_PIN13                    13U
#define GPIOB_PIN14                    14U
#define GPIOB_PIN15                    15U

#define GPIOC_PIN0                     0U
#define GPIOC_PIN1                     1U
#define GPIOC_PIN2                     2U
#define GPIOC_PIN3                     3U
#define GPIOC_PIN4                     4U
#define GPIOC_PIN5                     5U
#define GPIOC_PIN6                     6U
#define GPIOC_PIN7                     7U
#define GPIOC_PIN8                     8U
#define GPIOC_PIN9                     9U
#define GPIOC_PIN10                    10U
#define GPIOC_PIN11                    11U
#define GPIOC_PIN12                    12U
#define GPIOC_PIN13                    13U
#define GPIOC_PIN14                    14U
#define GPIOC_PIN15                    15U

#define GPIOD_PIN0                     0U
#define GPIOD_PIN1                     1U
#define GPIOD_PIN2                     2U
#define GPIOD_PIN3                     3U
#define GPIOD_PIN4                     4U
#define GPIOD_PIN5                     5U
#define GPIOD_PIN6                     6U
#define GPIOD_PIN7                     7U
#define GPIOD_PIN8                     8U
#define GPIOD_PIN9                     9U
#define GPIOD_PIN10                    10U
#define GPIOD_PIN11                    11U
#define GPIOD_PIN12                    12U
#define GPIOD_PIN13                    13U
#define GPIOD_PIN14                    14U
#define GPIOD_PIN15                    15U

#define GPIOF_DIG4                     0U
#define GPIOF_DIG3                     1U
#define GPIOF_PIN2                     2U
#define GPIOF_PIN3                     3U
#define GPIOF_PIN4                     4U
#define GPIOF_PIN5                     5U
#define GPIOF_PIN6                     6U
#define GPIOF_PIN7                     7U
#define GPIOF_PIN8                     8U
#define GPIOF_PIN9                     9U
#define GPIOF_PIN10                    10U
#define GPIOF_PIN11                    11U
#define GPIOF_PIN12                    12U
#define GPIOF_PIN13                    13U
#define GPIOF_PIN14                    14U
#define GPIOF_PIN15                    15U

/*
    IO lines assignments.
*/
#define LINE_DIG1                      PAL_LINE(GPIOA, 15U)
#define LINE_DIG2                      PAL_LINE(GPIOA, 0U)
#define LINE_DIG3                      PAL_LINE(GPIOF, 1U)
#define LINE_DIG4                      PAL_LINE(GPIOF, 0U)
#define LINE_DIG5                      PAL_LINE(GPIOA, 5U)
#define LINE_DIG6                      PAL_LINE(GPIOA, 10U)
#define LINE_DIG7                      PAL_LINE(GPIOA, 2U)
#define LINE_DIG8                      PAL_LINE(GPIOA, 1U)
#define LINE_I2C_SCL                   PAL_LINE(GPIOB, 6U)
#define LINE_I2C_SDA                   PAL_LINE(GPIOB, 7U)
#define LINE_LIGHT_EN                  PAL_LINE(GPIOA, 3U)
#define LINE_LIGHT_SENSE               PAL_LINE(GPIOA, 4U)
#define LINE_SEG_A                     PAL_LINE(GPIOB, 3U)
#define LINE_SEG_B                     PAL_LINE(GPIOA, 12U)
#define LINE_SEG_C                     PAL_LINE(GPIOB, 0U)
#define LINE_SEG_D                     PAL_LINE(GPIOA, 7U)
#define LINE_SEG_DP                    PAL_LINE(GPIOB, 1U)
#define LINE_SEG_E                     PAL_LINE(GPIOA, 6U)
#define LINE_SEG_F                     PAL_LINE(GPIOB, 4U)
#define LINE_SEG_G                     PAL_LINE(GPIOB, 5U)
#define LINE_SWCLK                     PAL_LINE(GPIOA, 14U)
#define LINE_SWDIO                     PAL_LINE(GPIOA, 13U)
#define LINE_SW_INC                    PAL_LINE(GPIOA, 8U)
#define LINE_SW_SET                    PAL_LINE(GPIOA, 9U)

/*
    I/O ports initial setup, this configuration is established soon after reset
    in the initialization code.
     Please refer to the STM32 Reference Manual for details.
*/
#define PIN_MODE_INPUT(n)              (0U << ((n) * 2U))
#define PIN_MODE_OUTPUT(n)             (1U << ((n) * 2U))
#define PIN_MODE_ALTERNATE(n)          (2U << ((n) * 2U))
#define PIN_MODE_ANALOG(n)             (3U << ((n) * 2U))
#define PIN_OD_LOW(n)                  (0U << (n))
#define PIN_OD_HIGH(n)                 (1U << (n))
#define PIN_OTYPE_PUSHPULL(n)          (0U << (n))
#define PIN_OTYPE_OPENDRAIN(n)         (1U << (n))
#define PIN_OSPEED_VERYLOW(n)          (0U << ((n) * 2U))
#define PIN_OSPEED_LOW(n)              (1U << ((n) * 2U))
#define PIN_OSPEED_MEDIUM(n)           (2U << ((n) * 2U))
#define PIN_OSPEED_HIGH(n)             (3U << ((n) * 2U))
#define PIN_PUPD_FLOATING(n)           (0U << ((n) * 2U))
#define PIN_PUPD_PULLUP(n)             (1U << ((n) * 2U))
#define PIN_PUPD_PULLDOWN(n)           (2U << ((n) * 2U))
#define PIN_AFIO_AF(n, v)              ((v) << (((n) % 8U) * 4U))

/*
 *  GPIOA setup:
 *
 * PA0  - DIG2                         (output).
 * PA1  - DIG8                         (output).
 * PA2  - DIG7                         (output).
 * PA3  - LIGHT_EN                     (output).
 * PA4  - LIGHT_SENSE                  (analog).
 * PA5  - DIG5                         (output).
 * PA6  - SEG_E                        (output).
 * PA7  - SEG_D                        (output).
 * PA8  - SW_INC                       (input pullup).
 * PA9  - SW_SET                       (input pullup).
 * PA10 - DIG6                         (output).
 * PA11 - PIN11                        (unused).
 * PA12 - SEG_B                        (output).
 * PA13 - SWDIO                        (af0).
 * PA14 - SWCLK                        (af0).
 * PA15 - DIG1                         (output).
*/
#define VAL_GPIOA_MODER                (PIN_MODE_OUTPUT(GPIOA_DIG2) | \
                                        PIN_MODE_OUTPUT(GPIOA_DIG8) | \
                                        PIN_MODE_OUTPUT(GPIOA_DIG7) | \
                                        PIN_MODE_OUTPUT(GPIOA_LIGHT_EN) | \
                                        PIN_MODE_ANALOG(GPIOA_LIGHT_SENSE) | \
                                        PIN_MODE_OUTPUT(GPIOA_DIG5) | \
                                        PIN_MODE_OUTPUT(GPIOA_SEG_E) | \
                                        PIN_MODE_OUTPUT(GPIOA_SEG_D) | \
                                        PIN_MODE_INPUT(GPIOA_SW_INC) | \
                                        PIN_MODE_INPUT(GPIOA_SW_SET) | \
                                        PIN_MODE_OUTPUT(GPIOA_DIG6) | \
                                        PIN_MODE_INPUT(GPIOA_PIN11) | \
                                        PIN_MODE_OUTPUT(GPIOA_SEG_B) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWDIO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWCLK) | \
                                        PIN_MODE_OUTPUT(GPIOA_DIG1))

#define VAL_GPIOA_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOA_DIG2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_DIG8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_DIG7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_LIGHT_EN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_LIGHT_SENSE) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_DIG5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SEG_E) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SEG_D) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SW_INC) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SW_SET) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_DIG6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SEG_B) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWDIO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWCLK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_DIG1))

#define VAL_GPIOA_OSPEEDR              (PIN_OSPEED_HIGH(GPIOA_DIG2) | \
                                        PIN_OSPEED_HIGH(GPIOA_DIG8) | \
                                        PIN_OSPEED_HIGH(GPIOA_DIG7) | \
                                        PIN_OSPEED_HIGH(GPIOA_LIGHT_EN) | \
                                        PIN_OSPEED_HIGH(GPIOA_LIGHT_SENSE) | \
                                        PIN_OSPEED_HIGH(GPIOA_DIG5) | \
                                        PIN_OSPEED_HIGH(GPIOA_SEG_E) | \
                                        PIN_OSPEED_HIGH(GPIOA_SEG_D) | \
                                        PIN_OSPEED_HIGH(GPIOA_SW_INC) | \
                                        PIN_OSPEED_HIGH(GPIOA_SW_SET) | \
                                        PIN_OSPEED_HIGH(GPIOA_DIG6) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOA_SEG_B) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWDIO) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWCLK) | \
                                        PIN_OSPEED_HIGH(GPIOA_DIG1))

#define VAL_GPIOA_PUPDR                (PIN_PUPD_FLOATING(GPIOA_DIG2) | \
                                        PIN_PUPD_FLOATING(GPIOA_DIG8) | \
                                        PIN_PUPD_FLOATING(GPIOA_DIG7) | \
                                        PIN_PUPD_FLOATING(GPIOA_LIGHT_EN) | \
                                        PIN_PUPD_FLOATING(GPIOA_LIGHT_SENSE) | \
                                        PIN_PUPD_FLOATING(GPIOA_DIG5) | \
                                        PIN_PUPD_FLOATING(GPIOA_SEG_E) | \
                                        PIN_PUPD_FLOATING(GPIOA_SEG_D) | \
                                        PIN_PUPD_PULLUP(GPIOA_SW_INC) | \
                                        PIN_PUPD_PULLUP(GPIOA_SW_SET) | \
                                        PIN_PUPD_FLOATING(GPIOA_DIG6) | \
                                        PIN_PUPD_FLOATING(GPIOA_PIN11) | \
                                        PIN_PUPD_FLOATING(GPIOA_SEG_B) | \
                                        PIN_PUPD_FLOATING(GPIOA_SWDIO) | \
                                        PIN_PUPD_FLOATING(GPIOA_SWCLK) | \
                                        PIN_PUPD_FLOATING(GPIOA_DIG1))

#define VAL_GPIOA_ODR                  (PIN_OD_LOW(GPIOA_DIG2) | \
                                        PIN_OD_LOW(GPIOA_DIG8) | \
                                        PIN_OD_LOW(GPIOA_DIG7) | \
                                        PIN_OD_LOW(GPIOA_LIGHT_EN) | \
                                        PIN_OD_LOW(GPIOA_LIGHT_SENSE) | \
                                        PIN_OD_LOW(GPIOA_DIG5) | \
                                        PIN_OD_LOW(GPIOA_SEG_E) | \
                                        PIN_OD_LOW(GPIOA_SEG_D) | \
                                        PIN_OD_LOW(GPIOA_SW_INC) | \
                                        PIN_OD_LOW(GPIOA_SW_SET) | \
                                        PIN_OD_LOW(GPIOA_DIG6) | \
                                        PIN_OD_LOW(GPIOA_PIN11) | \
                                        PIN_OD_LOW(GPIOA_SEG_B) | \
                                        PIN_OD_LOW(GPIOA_SWDIO) | \
                                        PIN_OD_LOW(GPIOA_SWCLK) | \
                                        PIN_OD_LOW(GPIOA_DIG1))

#define VAL_GPIOA_AFRL                 (PIN_AFIO_AF(GPIOA_DIG2, 0U) | \
                                        PIN_AFIO_AF(GPIOA_DIG8, 0U) | \
                                        PIN_AFIO_AF(GPIOA_DIG7, 0U) | \
                                        PIN_AFIO_AF(GPIOA_LIGHT_EN, 0U) | \
                                        PIN_AFIO_AF(GPIOA_LIGHT_SENSE, 0U) | \
                                        PIN_AFIO_AF(GPIOA_DIG5, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SEG_E, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SEG_D, 0U))

#define VAL_GPIOA_AFRH                 (PIN_AFIO_AF(GPIOA_SW_INC, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SW_SET, 0U) | \
                                        PIN_AFIO_AF(GPIOA_DIG6, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SEG_B, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWDIO, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWCLK, 0U) | \
                                        PIN_AFIO_AF(GPIOA_DIG1, 0U))

/*
 *  GPIOB setup:
 *
 * PB0  - SEG_C                        (output).
 * PB1  - SEG_DP                       (output).
 * PB2  - PIN2                         (unused).
 * PB3  - SEG_A                        (output).
 * PB4  - SEG_F                        (output).
 * PB5  - SEG_G                        (output).
 * PB6  - I2C_SCL                      (af1 opendrain).
 * PB7  - I2C_SDA                      (af1 opendrain).
 * PB8  - PIN8                         (unused).
 * PB9  - PIN9                         (unused).
 * PB10 - PIN10                        (unused).
 * PB11 - PIN11                        (unused).
 * PB12 - PIN12                        (unused).
 * PB13 - PIN13                        (unused).
 * PB14 - PIN14                        (unused).
 * PB15 - PIN15                        (unused).
*/
#define VAL_GPIOB_MODER                (PIN_MODE_OUTPUT(GPIOB_SEG_C) | \
                                        PIN_MODE_OUTPUT(GPIOB_SEG_DP) | \
                                        PIN_MODE_INPUT(GPIOB_PIN2) | \
                                        PIN_MODE_OUTPUT(GPIOB_SEG_A) | \
                                        PIN_MODE_OUTPUT(GPIOB_SEG_F) | \
                                        PIN_MODE_OUTPUT(GPIOB_SEG_G) | \
                                        PIN_MODE_ALTERNATE(GPIOB_I2C_SCL) | \
                                        PIN_MODE_ALTERNATE(GPIOB_I2C_SDA) | \
                                        PIN_MODE_INPUT(GPIOB_PIN8) | \
                                        PIN_MODE_INPUT(GPIOB_PIN9) | \
                                        PIN_MODE_INPUT(GPIOB_PIN10) | \
                                        PIN_MODE_INPUT(GPIOB_PIN11) | \
                                        PIN_MODE_INPUT(GPIOB_PIN12) | \
                                        PIN_MODE_INPUT(GPIOB_PIN13) | \
                                        PIN_MODE_INPUT(GPIOB_PIN14) | \
                                        PIN_MODE_INPUT(GPIOB_PIN15))

#define VAL_GPIOB_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOB_SEG_C) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_SEG_DP) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_SEG_A) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_SEG_F) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_SEG_G) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_I2C_SCL) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_I2C_SDA) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_PIN15))

#define VAL_GPIOB_OSPEEDR              (PIN_OSPEED_HIGH(GPIOB_SEG_C) | \
                                        PIN_OSPEED_HIGH(GPIOB_SEG_DP) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOB_SEG_A) | \
                                        PIN_OSPEED_HIGH(GPIOB_SEG_F) | \
                                        PIN_OSPEED_HIGH(GPIOB_SEG_G) | \
                                        PIN_OSPEED_HIGH(GPIOB_I2C_SCL) | \
                                        PIN_OSPEED_HIGH(GPIOB_I2C_SDA) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOB_PIN15))

#define VAL_GPIOB_PUPDR                (PIN_PUPD_FLOATING(GPIOB_SEG_C) | \
                                        PIN_PUPD_FLOATING(GPIOB_SEG_DP) | \
                                        PIN_PUPD_FLOATING(GPIOB_PIN2) | \
                                        PIN_PUPD_FLOATING(GPIOB_SEG_A) | \
                                        PIN_PUPD_FLOATING(GPIOB_SEG_F) | \
                                        PIN_PUPD_FLOATING(GPIOB_SEG_G) | \
                                        PIN_PUPD_FLOATING(GPIOB_I2C_SCL) | \
                                        PIN_PUPD_FLOATING(GPIOB_I2C_SDA) | \
                                        PIN_PUPD_FLOATING(GPIOB_PIN8) | \
                                        PIN_PUPD_FLOATING(GPIOB_PIN9) | \
                                        PIN_PUPD_FLOATING(GPIOB_PIN10) | \
                                        PIN_PUPD_FLOATING(GPIOB_PIN11) | \
                                        PIN_PUPD_FLOATING(GPIOB_PIN12) | \
                                        PIN_PUPD_FLOATING(GPIOB_PIN13) | \
                                        PIN_PUPD_FLOATING(GPIOB_PIN14) | \
                                        PIN_PUPD_FLOATING(GPIOB_PIN15))

#define VAL_GPIOB_ODR                  (PIN_OD_LOW(GPIOB_SEG_C) | \
                                        PIN_OD_LOW(GPIOB_SEG_DP) | \
                                        PIN_OD_LOW(GPIOB_PIN2) | \
                                        PIN_OD_LOW(GPIOB_SEG_A) | \
                                        PIN_OD_LOW(GPIOB_SEG_F) | \
                                        PIN_OD_LOW(GPIOB_SEG_G) | \
                                        PIN_OD_LOW(GPIOB_I2C_SCL) | \
                                        PIN_OD_LOW(GPIOB_I2C_SDA) | \
                                        PIN_OD_LOW(GPIOB_PIN8) | \
                                        PIN_OD_LOW(GPIOB_PIN9) | \
                                        PIN_OD_LOW(GPIOB_PIN10) | \
                                        PIN_OD_LOW(GPIOB_PIN11) | \
                                        PIN_OD_LOW(GPIOB_PIN12) | \
                                        PIN_OD_LOW(GPIOB_PIN13) | \
                                        PIN_OD_LOW(GPIOB_PIN14) | \
                                        PIN_OD_LOW(GPIOB_PIN15))

#define VAL_GPIOB_AFRL                 (PIN_AFIO_AF(GPIOB_SEG_C, 0U) | \
                                        PIN_AFIO_AF(GPIOB_SEG_DP, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOB_SEG_A, 0U) | \
                                        PIN_AFIO_AF(GPIOB_SEG_F, 0U) | \
                                        PIN_AFIO_AF(GPIOB_SEG_G, 0U) | \
                                        PIN_AFIO_AF(GPIOB_I2C_SCL, 1U) | \
                                        PIN_AFIO_AF(GPIOB_I2C_SDA, 1U))

#define VAL_GPIOB_AFRH                 (PIN_AFIO_AF(GPIOB_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN15, 0U))

/*
 *  GPIOC setup:
 *
 * PC0  - PIN0                         (unused).
 * PC1  - PIN1                         (unused).
 * PC2  - PIN2                         (unused).
 * PC3  - PIN3                         (unused).
 * PC4  - PIN4                         (unused).
 * PC5  - PIN5                         (unused).
 * PC6  - PIN6                         (unused).
 * PC7  - PIN7                         (unused).
 * PC8  - PIN8                         (unused).
 * PC9  - PIN9                         (unused).
 * PC10 - PIN10                        (unused).
 * PC11 - PIN11                        (unused).
 * PC12 - PIN12                        (unused).
 * PC13 - PIN13                        (unused).
 * PC14 - PIN14                        (unused).
 * PC15 - PIN15                        (unused).
*/
#define VAL_GPIOC_MODER                (PIN_MODE_INPUT(GPIOC_PIN0) | \
                                        PIN_MODE_INPUT(GPIOC_PIN1) | \
                                        PIN_MODE_INPUT(GPIOC_PIN2) | \
                                        PIN_MODE_INPUT(GPIOC_PIN3) | \
                                        PIN_MODE_INPUT(GPIOC_PIN4) | \
                                        PIN_MODE_INPUT(GPIOC_PIN5) | \
                                        PIN_MODE_INPUT(GPIOC_PIN6) | \
                                        PIN_MODE_INPUT(GPIOC_PIN7) | \
                                        PIN_MODE_INPUT(GPIOC_PIN8) | \
                                        PIN_MODE_INPUT(GPIOC_PIN9) | \
                                        PIN_MODE_INPUT(GPIOC_PIN10) | \
                                        PIN_MODE_INPUT(GPIOC_PIN11) | \
                                        PIN_MODE_INPUT(GPIOC_PIN12) | \
                                        PIN_MODE_INPUT(GPIOC_PIN13) | \
                                        PIN_MODE_INPUT(GPIOC_PIN14) | \
                                        PIN_MODE_INPUT(GPIOC_PIN15))

#define VAL_GPIOC_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOC_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN15))

#define VAL_GPIOC_OSPEEDR              (PIN_OSPEED_HIGH(GPIOC_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN15))

#define VAL_GPIOC_PUPDR                (PIN_PUPD_FLOATING(GPIOC_PIN0) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN1) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN2) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN3) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN4) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN5) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN6) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN7) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN8) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN9) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN10) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN11) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN12) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN13) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN14) | \
                                        PIN_PUPD_FLOATING(GPIOC_PIN15))

#define VAL_GPIOC_ODR                  (PIN_OD_LOW(GPIOC_PIN0) | \
                                        PIN_OD_LOW(GPIOC_PIN1) | \
                                        PIN_OD_LOW(GPIOC_PIN2) | \
                                        PIN_OD_LOW(GPIOC_PIN3) | \
                                        PIN_OD_LOW(GPIOC_PIN4) | \
                                        PIN_OD_LOW(GPIOC_PIN5) | \
                                        PIN_OD_LOW(GPIOC_PIN6) | \
                                        PIN_OD_LOW(GPIOC_PIN7) | \
                                        PIN_OD_LOW(GPIOC_PIN8) | \
                                        PIN_OD_LOW(GPIOC_PIN9) | \
                                        PIN_OD_LOW(GPIOC_PIN10) | \
                                        PIN_OD_LOW(GPIOC_PIN11) | \
                                        PIN_OD_LOW(GPIOC_PIN12) | \
                                        PIN_OD_LOW(GPIOC_PIN13) | \
                                        PIN_OD_LOW(GPIOC_PIN14) | \
                                        PIN_OD_LOW(GPIOC_PIN15))

#define VAL_GPIOC_AFRL                 (PIN_AFIO_AF(GPIOC_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN7, 0U))

#define VAL_GPIOC_AFRH                 (PIN_AFIO_AF(GPIOC_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN15, 0U))

/*
 *  GPIOD setup:
 *
 * PD0  - PIN0                         (unused).
 * PD1  - PIN1                         (unused).
 * PD2  - PIN2                         (unused).
 * PD3  - PIN3                         (unused).
 * PD4  - PIN4                         (unused).
 * PD5  - PIN5                         (unused).
 * PD6  - PIN6                         (unused).
 * PD7  - PIN7                         (unused).
 * PD8  - PIN8                         (unused).
 * PD9  - PIN9                         (unused).
 * PD10 - PIN10                        (unused).
 * PD11 - PIN11                        (unused).
 * PD12 - PIN12                        (unused).
 * PD13 - PIN13                        (unused).
 * PD14 - PIN14                        (unused).
 * PD15 - PIN15                        (unused).
*/
#define VAL_GPIOD_MODER                (PIN_MODE_INPUT(GPIOD_PIN0) | \
                                        PIN_MODE_INPUT(GPIOD_PIN1) | \
                                        PIN_MODE_INPUT(GPIOD_PIN2) | \
                                        PIN_MODE_INPUT(GPIOD_PIN3) | \
                                        PIN_MODE_INPUT(GPIOD_PIN4) | \
                                        PIN_MODE_INPUT(GPIOD_PIN5) | \
                                        PIN_MODE_INPUT(GPIOD_PIN6) | \
                                        PIN_MODE_INPUT(GPIOD_PIN7) | \
                                        PIN_MODE_INPUT(GPIOD_PIN8) | \
                                        PIN_MODE_INPUT(GPIOD_PIN9) | \
                                        PIN_MODE_INPUT(GPIOD_PIN10) | \
                                        PIN_MODE_INPUT(GPIOD_PIN11) | \
                                        PIN_MODE_INPUT(GPIOD_PIN12) | \
                                        PIN_MODE_INPUT(GPIOD_PIN13) | \
                                        PIN_MODE_INPUT(GPIOD_PIN14) | \
                                        PIN_MODE_INPUT(GPIOD_PIN15))

#define VAL_GPIOD_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOD_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN15))

#define VAL_GPIOD_OSPEEDR              (PIN_OSPEED_HIGH(GPIOD_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN15))

#define VAL_GPIOD_PUPDR                (PIN_PUPD_FLOATING(GPIOD_PIN0) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN1) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN2) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN3) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN4) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN5) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN6) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN7) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN8) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN9) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN10) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN11) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN12) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN13) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN14) | \
                                        PIN_PUPD_FLOATING(GPIOD_PIN15))

#define VAL_GPIOD_ODR                  (PIN_OD_LOW(GPIOD_PIN0) | \
                                        PIN_OD_LOW(GPIOD_PIN1) | \
                                        PIN_OD_LOW(GPIOD_PIN2) | \
                                        PIN_OD_LOW(GPIOD_PIN3) | \
                                        PIN_OD_LOW(GPIOD_PIN4) | \
                                        PIN_OD_LOW(GPIOD_PIN5) | \
                                        PIN_OD_LOW(GPIOD_PIN6) | \
                                        PIN_OD_LOW(GPIOD_PIN7) | \
                                        PIN_OD_LOW(GPIOD_PIN8) | \
                                        PIN_OD_LOW(GPIOD_PIN9) | \
                                        PIN_OD_LOW(GPIOD_PIN10) | \
                                        PIN_OD_LOW(GPIOD_PIN11) | \
                                        PIN_OD_LOW(GPIOD_PIN12) | \
                                        PIN_OD_LOW(GPIOD_PIN13) | \
                                        PIN_OD_LOW(GPIOD_PIN14) | \
                                        PIN_OD_LOW(GPIOD_PIN15))

#define VAL_GPIOD_AFRL                 (PIN_AFIO_AF(GPIOD_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN7, 0U))

#define VAL_GPIOD_AFRH                 (PIN_AFIO_AF(GPIOD_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN15, 0U))

/*
 *  GPIOF setup:
 *
 * PF0  - DIG4                         (output).
 * PF1  - DIG3                         (output).
 * PF2  - PIN2                         (unused).
 * PF3  - PIN3                         (unused).
 * PF4  - PIN4                         (unused).
 * PF5  - PIN5                         (unused).
 * PF6  - PIN6                         (unused).
 * PF7  - PIN7                         (unused).
 * PF8  - PIN8                         (unused).
 * PF9  - PIN9                         (unused).
 * PF10 - PIN10                        (unused).
 * PF11 - PIN11                        (unused).
 * PF12 - PIN12                        (unused).
 * PF13 - PIN13                        (unused).
 * PF14 - PIN14                        (unused).
 * PF15 - PIN15                        (unused).
*/
#define VAL_GPIOF_MODER                (PIN_MODE_OUTPUT(GPIOF_DIG4) | \
                                        PIN_MODE_OUTPUT(GPIOF_DIG3) | \
                                        PIN_MODE_INPUT(GPIOF_PIN2) | \
                                        PIN_MODE_INPUT(GPIOF_PIN3) | \
                                        PIN_MODE_INPUT(GPIOF_PIN4) | \
                                        PIN_MODE_INPUT(GPIOF_PIN5) | \
                                        PIN_MODE_INPUT(GPIOF_PIN6) | \
                                        PIN_MODE_INPUT(GPIOF_PIN7) | \
                                        PIN_MODE_INPUT(GPIOF_PIN8) | \
                                        PIN_MODE_INPUT(GPIOF_PIN9) | \
                                        PIN_MODE_INPUT(GPIOF_PIN10) | \
                                        PIN_MODE_INPUT(GPIOF_PIN11) | \
                                        PIN_MODE_INPUT(GPIOF_PIN12) | \
                                        PIN_MODE_INPUT(GPIOF_PIN13) | \
                                        PIN_MODE_INPUT(GPIOF_PIN14) | \
                                        PIN_MODE_INPUT(GPIOF_PIN15))

#define VAL_GPIOF_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOF_DIG4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_DIG3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN15))

#define VAL_GPIOF_OSPEEDR              (PIN_OSPEED_HIGH(GPIOF_DIG4) | \
                                        PIN_OSPEED_HIGH(GPIOF_DIG3) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN15))

#define VAL_GPIOF_PUPDR                (PIN_PUPD_FLOATING(GPIOF_DIG4) | \
                                        PIN_PUPD_FLOATING(GPIOF_DIG3) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN2) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN3) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN4) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN5) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN6) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN7) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN8) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN9) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN10) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN11) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN12) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN13) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN14) | \
                                        PIN_PUPD_FLOATING(GPIOF_PIN15))

#define VAL_GPIOF_ODR                  (PIN_OD_LOW(GPIOF_DIG4) | \
                                        PIN_OD_LOW(GPIOF_DIG3) | \
                                        PIN_OD_LOW(GPIOF_PIN2) | \
                                        PIN_OD_LOW(GPIOF_PIN3) | \
                                        PIN_OD_LOW(GPIOF_PIN4) | \
                                        PIN_OD_LOW(GPIOF_PIN5) | \
                                        PIN_OD_LOW(GPIOF_PIN6) | \
                                        PIN_OD_LOW(GPIOF_PIN7) | \
                                        PIN_OD_LOW(GPIOF_PIN8) | \
                                        PIN_OD_LOW(GPIOF_PIN9) | \
                                        PIN_OD_LOW(GPIOF_PIN10) | \
                                        PIN_OD_LOW(GPIOF_PIN11) | \
                                        PIN_OD_LOW(GPIOF_PIN12) | \
                                        PIN_OD_LOW(GPIOF_PIN13) | \
                                        PIN_OD_LOW(GPIOF_PIN14) | \
                                        PIN_OD_LOW(GPIOF_PIN15))

#define VAL_GPIOF_AFRL                 (PIN_AFIO_AF(GPIOF_DIG4, 0U) | \
                                        PIN_AFIO_AF(GPIOF_DIG3, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN7, 0U))

#define VAL_GPIOF_AFRH                 (PIN_AFIO_AF(GPIOF_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN15, 0U))

#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */